description: >
  Example teams-notification orb usage in the code

usage:
  version: 2.1
  orbs:
    teams-notification: shureeck/teams-notification@1.1.0
jobs:
  run-tests:
    steps:
      - run:
          name: Test run command.
          description: Command that executes tests
          command: yarn test
      - teams-notification/status:
          teams_url: "https://microsoft.teams.workflow.url"
          failed_message: "Tests failed"
          passed_message: "Tests passed"
          report_url: "http://localhost/reports/index.html"
  workflows:
    use-my-orb:
      jobs:
        - run-tests
